lyft/flinkk8soperator

.travis.yml
Just noticed, the PRs merged to master are not pushing docker images.
https://travis-ci.org/lyft/flinkk8soperator/builds/540614153?utm_source=github_status&utm_medium=notification
In some cases, the branch is set to master even though it is a PR: https://travis-ci.org/lyft/flinkk8soperator/builds/540887580 so explicitly adding push check
Discussion from here: https://github.com/travis-ci/travis-ci/issues/8767
=> Fix the travis condition to make docker hub push on merge to master

deploy/crd.yaml
This PR adds additional printer columns to the CRD to make it easier to quickly see the status of flink applications.
Example output:
```
$ kubectl get flinkapplications
NAME                PHASE     CLUSTER HEALTH   JOB HEALTH   JOB RESTARTS   AGE
operator-test-app   Running   Green            Green        2             35m
$ kubectl get flinkapplications -owide
NAME                PHASE     CLUSTER HEALTH   JOB HEALTH   HEALTHY TMS   TOTAL TMS   JOB RESTARTS   AGE
operator-test-app   Running   Green            Green        1             1           2             36m
```
=> [STRMCMP-507] Add additional printer columns

deploy/role.yaml, docs/quick-start-guide.md
1. I tried out the project and found out an issue with starting a Flink app:
```
time="2019-06-03T18:10:48Z" level=error msg="Jobmanager deployment creation failed deployments.apps \"wordcount-operator-example-f5b2ddb2-jm\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: no RBAC policy matched, <nil>" app_name=wordcount-operator-example ns=flink-operator phase=
```
The reason is that the finalizer permissions were not properly given to the ClusterRole. This PR fixed it. (Note: I'm on OpenShift. Not sure if it's OpenShift-specific but this change shouldn't break non-OpenShift k8s).
2. Added some notes about resource requirements when deploying the operator. I wasn't able to deploy initially because of lack of resources. I …
=> Added finalizer permissions

deploy/role.yaml
Signed-off-by: Joshua Benjamin <joshuabnjmn@gmail.com>
=> Add delete verb for service

.travis.yml, Dockerfile, README.md, docs/quick-start-guide.md, examples/wordcount/flink-conf.yaml, examples/wordcount/flink-operator-custom-resource.yaml, integ/operator-test-app/flink-conf.yaml
1. Updated Go to the most recent version (i.e. 1.12.5). 1.10.4 is way too old.
2. Updated the URL for S2I. The previous URL was pointing to a location that redirected to the current URL.
3. It's always good to specify the namespace for a namespaced resource. So a namespace `default` is added to the sample FlinkApplication YAML and READMEs are updated accordingly. Previously, without namespace specified, the CR object was also created in `default` namespace by default. But the README was assuming it was in the `flink-operator` namespace.
4. Changed `jobmanager.web.upload.dir` to `web.upload.dir`. The former is now deprecated.
=> Minor fixes and improvements

docs/crd.md, pkg/apis/app/v1alpha1/types.go, pkg/apis/app/v1alpha1/zz_generated.deepcopy.go, pkg/controller/flink/job_manager_controller.go, pkg/controller/flink/task_manager_controller.go
Signed-off-by: Joshua Benjamin <joshuabnjmn@gmail.com>
=> Add node selectors to job and task config

pkg/controller/flinkapplication/flink_state_machine.go, pkg/controller/flinkapplication/flink_state_machine_test.go
The operator currently panics if it receives an application callback with an invalid phase.
=> Handle invalid phases in the Flink state machine

Gopkg.lock, Gopkg.toml, pkg/controller/flink/client/api.go, pkg/controller/flink/client/api_test.go
- Fixes the incorrect logging from Resty library.
- Removes retry from Patch and Post requests, as Flink POST request is not idempotent.
- Separate timeout for Get vs Post request.
Sample logs in json format: 
```
{"json":{"app_name":"taskfailurejob","ns":"default","phase":"SubmittingJob","src":"api.go:147"},"level":"info","msg":"RESTY 2019/06/14 13:48:18 ERROR Get http://localhost:8001/api/v1/namespaces/default/services/taskfailurejob-949b65b0:8081/proxy/overview: dial tcp [::1]:8001: connect: connection refused, Attempt 3","ts":"2019-06-14T13:48:18-07:00"}
{"json":{"app_name":"taskfailurejob","ns":"default","phase":"SubmittingJob","src":"api.go:147"},"level":"info","msg":"RESTY 2019/06/14 13:48:18 ERROR Get http://localhost:8001/api/v1/namespaces/flink-operator/services/wordcount-operato …
```
=> Fix Resty logging, timeout and retry configuration

pkg/controller/flink/container_utils.go, pkg/controller/flink/flink.go, pkg/controller/flink/flink_test.go, pkg/controller/flink/job_manager_controller.go, pkg/controller/flink/mock/mock_flink.go, pkg/controller/flink/task_manager_controller.go, pkg/controller/flinkapplication/flink_state_machine.go, pkg/controller/flinkapplication/flink_state_machine_test.go, pkg/controller/k8/cluster.go, pkg/controller/k8/mock/mock_k8.go
Currently, if we successfully delete just one of the two (TM and JM) deployments during old-cluster clean-up, on the next run we will not be able to successfully query the deployment due to the check in GetCurrentAndOldDeploymentsForApp that we have 1 JM and 1 TM for each. This means that we will never clean up the old deployment. This may also cause us to not clean up the old versioned service.
This PR refactors the cleanup process to query for all old resources (deployments and services) and delete them.
Note that this is a (slightly) incompatible change. As we now rely on labels to find old services that need to be cleaned up, this operator will not be able to clean up services created by a previous version—they will need to be deleted manually after the upgrade.
=> [STRMCMP-509] Make old cluster clean-up idempotent

pkg/controller/flinkapplication/flink_state_machine.go, pkg/controller/flinkapplication/flink_state_machine_test.go
Currently, if a user creates a new FlinkApplication for which we can't successfully submit the job (e.g., the jar name is wrong, the job crashes on startup, the specified savepoint doesn't exist, etc.) the user will not be able to then delete the FlinkApplication without changing the DeleteMode to None. This is because we do not set the DeployHash until after job submission, which prevents us from querying the versioned cluster. This PR addresses that by allowing immediate deletion of a cluster when the DeployHash is not set.
It also addresses the issue in #13 by allowing deletion when there has been a successful deploy at some point, but at delete time no jobs are running.
=> [STRMCMP-544] Allow FlinkApplications to be deleted when job submission fails

deploy/crd.yaml, integ/test_app.yaml, pkg/apis/app/v1alpha1/types.go
Adding Validation of flink application custom objects using openAPIV3Schema. Helps fail the creation/update of custom resources with invalid format.
=> Adding openAPIV3Schema Validation for the Flink application custom resource

cmd/flinkk8soperator/cmd/root.go, pkg/controller/config/config.go, pkg/controller/flink/flink.go, pkg/controller/flink/flink_test.go, pkg/controller/flink/mock/mock_flink.go, pkg/controller/flinkapplication/controller.go, pkg/controller/flinkapplication/flink_state_machine.go, pkg/controller/k8/utils.go
This replaces the current implementation of creating events manually through the Client.
```
Type    Reason  Age   From              Message
----    ------  ----  ----              -------
Normal  Create  32s   flinkK8sOperator  Flink cluster created
Normal  Create  20s   flinkK8sOperator  Flink job submitted to cluster with id 519428ccbadc58365924f1bba55324b1
Normal  Update  14s   flinkK8sOperator  Flink cluster created
Type    Reason  Age   From              Message
----    ------  ----  ----              -------
Normal  Create  34s   flinkK8sOperator  Flink cluster created
Normal  Create  22s   flinkK8sOperator  Flink job submitted to cluster with id 519428ccbadc58365924f1bba55324b1
Normal  Update  16s   flinkK8sOperator  Flink cluster created```
=> Use EventRecorder instead of emitting events manually

pkg/controller/flink/flink.go, pkg/controller/flink/flink_test.go, pkg/controller/flinkapplication/flink_state_machine.go
New Logic:
- Uses the value of availableReplicas to update `NumberOfTaskManagers`
- `HealthyTaskManagers` is still obtained from the API response
- Health logic is now compared between `HealthyTaskManagers`, and number of replicas expected.
Cluster status is also updated when in `SubmittingJob` state.
Not updating the ClusterStatus in `ClusterStarting`, as there could be multiple clusters, and hence removed the check.
=> Update logic around number and healthy task managers in status

deploy/crd.yaml, docs/crd.md, pkg/apis/app/v1alpha1/types.go, pkg/controller/flink/client/entities.go, pkg/controller/flink/flink.go, pkg/controller/flink/flink_test.go
This PR adds support for providing the `--allowNonRestoredState` flag to a submit job request. If, for some reason, that state isn't persistent between versions of a job, the deployment will fail entirely.
The addition here adds a `allowNonRestoredState` boolean flag to the `crd.yaml`.
=> Add support for non restored state on job submission

Gopkg.lock, Gopkg.toml, cmd/flinkk8soperator/cmd/root.go, local_config.yaml, pkg/client/clientset/versioned/clientset.go, pkg/client/clientset/versioned/fake/clientset_generated.go, pkg/client/clientset/versioned/fake/register.go, pkg/client/clientset/versioned/scheme/register.go, pkg/client/clientset/versioned/typed/app/v1alpha1/fake/fake_flinkapplication.go, pkg/client/clientset/versioned/typed/app/v1alpha1/flinkapplication.go, pkg/controller/flink/flink.go, pkg/controller/flink/flink_test.go, pkg/controller/flink/job_manager_controller_test.go, pkg/controller/flink/task_manager_controller_test.go, pkg/controller/flinkapplication/controller.go, pkg/controller/flinkapplication/flink_state_machine.go, pkg/controller/k8/cluster.go
***[Backward Incompatible]***
The hash value computation has changed. Deploying this version of operator will cause rollover/restart of applications.
This PR upgrades the version of controller runtime. Uses a fixed version of Flytestdlib.
Flink operator will now support watching applications across multiple namespaces, previously it was either a single namespace or all namespaces.
=> Upgrade controller runtime and Multi Namespace support for Flink operator

cmd/flinkk8soperator/cmd/root.go
Global flags have stopped working after [this change](https://github.com/lyft/flinkk8soperator/commit/f9206646aaffb7763657ec9e794bc979b0b4722b)
Use `klog.InitFlags(nil)` explicitly for initializing global flags as we no longer use `init()` method to register the flags
Refer here: https://github.com/kubernetes/klog/blob/master/README.md#how-to-use-klog
```aswaminathan-mbp151:flinkk8soperator aswaminathan$ go run cmd/flinkk8soperator/main.go  -h
Warn: No metricsProvider set for the workqueue
INFO[0000] ------------------------------------------------------------------------ 
INFO[0000] App [flinkK8sOperator], Version [unknown], BuildSHA [unknown], BuildTS [2019-07-08 12:27:54.869562 -0700 PDT m=+0.005832719] 
INFO[0000] ------------------------------------------------------------------------ …
```
=> Initialize Klog explicitly using InitFlags

pkg/controller/flinkapplication/controller.go, pkg/controller/k8/cluster.go
- Add create/update/delete success and failure metrics for Kubernetes objects - in turn can help identify etcd issues/bugs.
- Metrics for deployments fetched from Cache/Client
=> Add more metrics to Flinkk8soperator

Gopkg.lock, pkg/controller/flink/container_utils.go, pkg/controller/flink/flink.go, pkg/controller/flink/flink_test.go, pkg/controller/flink/job_manager_controller.go, pkg/controller/flink/job_manager_controller_test.go, pkg/controller/flink/task_manager_controller.go, pkg/controller/flink/task_manager_controller_test.go
We somehow ended up with two codepaths for finding the current deployments associated with an application. The one used by the status checks was using the current application hash, not the DeployHash, to find the deployments.. This caused it to fail for applications that had been rolled back with error logs like
```
ERRO[0000] Unable to find task manager deployment        app_name=operator-test-app ns=default phase=DeployFailed src="flink.go:461"
```
This PR removes that function and moves the callers to `GetCurrentDeploymentsForApp`, which also has the benefit of making the handling code a bit simpler.
=> Find the correct deployments for readiness and status checks

pkg/controller/flink/flink.go, pkg/controller/flink/mock/mock_flink.go, pkg/controller/flinkapplication/flink_state_machine.go
This PR makes two improvements to the events that the operator emits for FlinkApplication resources.
First, it ensures that all deploy-related events are unique to a particular deploy (generally by including the hash of the resource in the message). This ensures that if two deploys occur in rapid succession, the second one will still produce events (if more than 10 events with the same message are emitted within a 10 minute period, later events are dropped). This prevents a situation where a developer does a deploy, encounters an error that produces several events, tries the deploy again but this time doesn't seen any events because we have already exhausted our limit.
The second change is to fix the reason field of the events we emit. When I originally added events I misunderstood what …
=> [STRMCMP-558] Event improvements

examples/wordcount/Dockerfile, examples/wordcount/docker-entrypoint.sh, integ/README.md, integ/operator-test-app/Dockerfile, integ/operator-test-app/docker-entrypoint.sh, integ/simple_test.go, integ/test_app.yaml, pkg/controller/flink/config.go, pkg/controller/flink/container_utils.go, pkg/controller/flink/flink_test.go, pkg/controller/flink/job_manager_controller.go, pkg/controller/flink/job_manager_controller_test.go, pkg/controller/flink/task_manager_controller.go, pkg/controller/flink/task_manager_controller_test.go
We want the ability to assign some of the Flink config values dynamically based on values from host name, Ip, etc.
From an overall observation, currently both the operator and the image understands that jobmanager and task manager behave differently. In this particular context, we want the "jobmanager.rpc.address" to be pod name on the Job manager and service name on the task manager. 
I iterated across multiple options and arrived at this. Also update the Dockerfile in examples and test to reflect the same. The changes below can be simpler and all the responsibility of setting correct values can be delegated to the image. But I believe since operator is already ironing lots of things out and setting things correctly, I moved some of the logic to the operator. But I understand this is …
=> [Backward Incompatible] Add env variables for Flink managers and fix for JM HA

pkg/controller/flink/client/error_handler.go, pkg/controller/flink/client/error_handler_test.go, pkg/controller/flinkapplication/flink_state_machine.go, pkg/controller/flinkapplication/flink_state_machine_test.go
Currently, the `LastSeenError` is updated (on the k8s object) only if the error returned by a `handle<State>` call is not nil. This is a problem when `handle<State>` call succeeds after the first retry and `appErr` is now nil, the k8s object does not get updated and the error will continue to be retried until retries are exhausted. 
Changelog:
- Modify getAndUpdateError to compareAndUpdateError, which compares current and older error. If they are both nil, no updates to the k8s object are made. In all other cases, the k8s object is updated
- Call compareAndUpdateError irrespective of the value of appError
- Bug fix for the `IsTimeToRetry` logic which was evaluating a wrong value before and updated the corresponding test to not give false positives.
=> Change error update logic and fix retry bug

deploy/flinkk8soperator.yaml
We have changed the Docker file in our examples. Our current examples only work with the latest release of the operator (due to the latest Flink HA issue fix).
cc @mwylde @glaksh100
=> Update to the latest Flinkk8soperator release

docs/crd.md
This updates the documentation to match the json/yaml serialization format to prevent confusion.
It also matches the validation defined here: https://github.com/lyft/flinkk8soperator/blob/master/deploy/crd.yaml#L16
cc @tweise
=> Update the documentation to reflect json naming schema

deploy/crd.yaml
From [the docs](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#type), floating point numbers have the type `number`, not `float`.
=> Change invalid 'float' types to 'number' in crd validation schema

docs/crd.md, integ/simple_test.go, integ/test.sh, pkg/apis/app/v1alpha1/types.go, pkg/controller/flinkapplication/flink_state_machine.go, pkg/controller/flinkapplication/flink_state_machine_test.go
This PR adds the ability for a user to cancel an ongoing deploy/update. This is done in the following way:
- By adding a `CancelDeploy` to the Spec. The user sets this to be True to cancel the deploy. 
- When `CancelDeploy` is set to True, `shouldRollback` evaluates to True and moves the application to a `DeployFailed` state. 
- Either un-setting or setting `CancelDeploy` to False enables the deploy to be continued (as would be the case when we fix forward from DeployFailed)
- An integration test case is added to `simple_test.sh` for this workflow.
- CRD doc is updated to include `CancelDeploy`
Alternatively, I could have added an extra state (like `DeployCancelled`) but felt that that would have been quite a bit of code duplication as it'd be very similar to the DeployFailed state. Happy …
=> Add a ForceRollback option to CRD

docs/quick-start-guide.md, examples/wordcount/flink-operator-custom-resource.yaml
This PR fixes use of latest tag in example wordcount. I have also update the quick start guide with latest CRD status and events output
Related issue: https://github.com/lyft/flinkk8soperator/issues/53
=> Fix image tag and update documentation

pkg/controller/flink/client/error_handler.go, pkg/controller/flink/client/error_handler_test.go
TL;DR of issue and fix: https://play.golang.org/p/u3xKnyRNkl8. The min comparison was not happening on the same time scale.
=> Fix retry maxbackoff issue

pkg/controller/flink/container_utils.go, pkg/controller/flink/flink_test.go, pkg/controller/flink/job_manager_controller_test.go, pkg/controller/flink/task_manager_controller_test.go
Currently, whenever we upgrade "client-go", "apimachinery", "api"  the hash value also changes.
This PR changes the hashing mechanism
I have tested this across these two SHAs - `9aaa992bf12ecd0577a4b0f7dfb1c248a93d47ea` and `f9206646aaffb7763657ec9e794bc979b0b4722b`. The hash does not change.
=> [Backward Incompatible] Modifying Hash function to be consistent

Gopkg.lock, Gopkg.toml
Build on the master is failing.
```
GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o /artifacts/flinkoperator ./cmd/flinkk8soperator/main.go
307pkg/controller/flink/container_utils.go:7:2: cannot find package "github.com/benlaurie/objecthash/go/objecthash" in any of:
308	/go/src/github.com/lyft/flinkk8soperator/vendor/github.com/benlaurie/objecthash/go/objecthash (vendor tree)
309	/usr/local/go/src/github.com/benlaurie/objecthash/go/objecthash (from $GOROOT)
310	/go/src/github.com/benlaurie/objecthash/go/objecthash (from $GOPATH)
311make: *** [Makefile:16: linux_compile] Error 1
312The command '/bin/sh -c make linux_compile' returned a non-zero code: 2
313boilerplate/lyft/docker_build/Makefile:7: recipe for target 'dockerhub_push' failed
314make: *** [dockerhub_push] Error 2
```
=> Fix objecthash dependency

examples/wordcount/Dockerfile
Adding S3 client libraries (simply copying them from `opt` to `lib` on the Flink installation folder) so that examples can make use of S3 filesystems (`s3a://` and `s3p://` schemes)
=> Adding S3 client libraries

deploy/crd.yaml
This change adds support for multiple versions (v1alpha1 and v1beta1) in the crd, as described [here](https://v1-14.docs.kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definition-versioning/#specify-multiple-versions).
The latest version of v1alpha1 and v1beta1 are compatible (i.e., the current version of the operator can handle both) so this allows the migration to v1beta1 to be non-breaking for existing users.
=> Add support for multiple versions

pkg/controller/k8/cluster.go
We missed passing namespace to ListOptions.
Thanks @yuchaoran2011 for catching
=> Pass the namespace in the client.ListOptions

pkg/controller/flink/container_utils.go, pkg/controller/flink/container_utils_test.go, pkg/controller/flink/flink.go, pkg/controller/flink/flink_test.go, pkg/controller/flink/job_manager_controller.go, pkg/controller/flink/task_manager_controller.go, pkg/controller/k8/cluster.go
Under deploymentEquals,
The volume returned from the API contains `EmptyDirVolumeSource` set to empty object, even though it is set to nil when creation. 
There are other cases as well like `defaultMode: 420` in configmap.
Removing the equality checks, as hash collisions are rare, and equality check is not right
=> For now the equality checks for Deployment matches

pkg/controller/flink/config.go, pkg/controller/flink/config_test.go
Flink's config format looks like YAML, but is not _really_ YAML. The [parser](https://github.com/apache/flink/blob/9e6ff81e22d6f5f04abb50ca1aea84fd2542bf9d/flink-core/src/main/java/org/apache/flink/configuration/GlobalConfiguration.java#L181) is extremely simple, and basically operates just by splitting each line on  `: ` and treating the first part as a key and the second as the value.
Currently we are using gopkg.in/yaml.v2 to render the config. However, this breaks in the case of long strings with spaces (like 
```
-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=39000 -XX:+UseG1GC
```
). In that case, yaml.v2 will convert the space into a line break (https://github.com/go-yaml/yaml/issues/166), producing output like
```yaml
env.java.opts.jobmanager: …
```
=> [STRMCMP-610] Fix flink config rendering

Gopkg.lock, pkg/controller/flinkapplication/flink_state_machine.go, pkg/controller/flinkapplication/flink_state_machine_test.go
Currently certain rollback triggers (like the default time-based one) do not report anything back to the user about _why_ the deploy was rolled-back. For example:
```
Normal   CreatingCluster   12m    flinkK8sOperator  Creating Flink cluster for deploy fe5e6e29
Warning  RolledBackDeploy  6m50s  flinkK8sOperator  Successfull rolled back deploy fe5e6e29
Normal   ToreDownCluster   6m50s  flinkK8sOperator  Deleted old cluster with hash fe5e6e29
```
From the events it looks like everything was fine, until the operator randomly decided to roll back.
This PR ensures that we also log a reason for the rollback.
=> [STRMCMP-611] Log events for all rollback situations

integ/test.sh, integ/utils/utils.go, pkg/controller/flinkapplication/flink_state_machine.go, pkg/controller/flinkapplication/flink_state_machine_test.go
Currently, if a flinkapplication is being deleted with `DeleteMode: Savepoint` and the savepoint operation is failing, we will retry endlessly with no delay on the savepoint operation. This is because in that case, we don't return an error back to the error management system of the state machine.
This PR fixes that by properly returning an error for that situation. This causes us to do retry with exponential backoff instead of on every statemachine iteration.
It also should fix the "exceeded the maximum log length" integration test failures, which are caused by endless logging of the retries.
=> [STRMCMP-616] Use error retrying system for savepoint errors during deletion

pkg/apis/app/v1alpha1/types.go, pkg/apis/app/v1beta1/types.go, pkg/controller/flink/client/api.go, pkg/controller/flink/flink.go, pkg/controller/flink/flink_test.go
This PR adds the cluster and job overview URLs to the cluster and job status respectively. The objective is to provide users easy access to the required Web UI. This information can also be used in any other CI/D tooling used to support Flink applications on k8s.  
Example output:
```yaml
Status:
Cluster Status:
Available Task Slots:     1
Cluster Overview URL:     http://localhost:8001/api/v1/namespaces/default/services/simpleflinkk8s:8081/proxy/#/overview
Health:                   Green
Healthy Task Managers:    1
Number Of Task Managers:  1
Number Of Task Slots:     2
Deploy Hash:                18051096
Failed Deploy Hash:
Job Status:
Completed Checkpoint Count:  10
Entry Class:                 com.lyft.OperatorTestApp
Failed Checkpoint Count:     0
Health:                      Green …
```
=> Add Web UI information to status

pkg/controller/flink/client/api.go, pkg/controller/flink/client/api_test.go, pkg/controller/flink/client/error_handler.go, pkg/controller/flink/client/error_handler_test.go
When the user specifies a wrong entry class or the main method throws an exception, the Flink API returns back a 500 error with a `org.apache.flink.client.program.ProgramInvocationException`.
In order to minimize downtime, we want to rollback immediately in this case rather than waiting for retries to be exhausted.
This PR also improves the error reporting a bit for this situation. Previously, the error wrapping functions took an array of strings which were reported verbatim. This produced confusing output that implied that the API itself was returning an array. As all actual calls to these methods were using either 0 or 1 arguments, I've split it out into those particular cases.
=> [STRMCMP-569] Failures during job startup should trigger immediate rollback

Gopkg.lock, Gopkg.toml, pkg/controller/k8/cluster.go
Upgrades the controller runtime library from `v0.2.0-beta.3` to `v0.2.0`.
cc @yuchaoran2011 - https://github.com/lyft/flinkk8soperator/issues/93
=> Upgrade to Controller Runtime v0.2.0

pkg/controller/flink/client/error_handler.go
This PR updates the field name in error_handler.go to be consistent with the one defined in config.go https://github.com/lyft/flinkk8soperator/blob/master/pkg/controller/config/config.go#L26
=> Keep config names constant across error_handler and config

.travis.yml, integ/simple_test.go, integ/test_app.yaml, integ/utils/utils.go, pkg/controller/flink/client/error_handler.go, pkg/controller/flinkapplication/flink_state_machine.go
This PR includes a bunch of improvements to integration test stability and usability.
* Improves the "are all tasks running" logic
* Retries FlinkApplication updates on conflicts 
* Uses a bad image for the force rollback test instead of too much memory
* Updates test VM to bionic
* Added more log lines to help diagnose where tests get stuck
* Logging is now plaintext instead of json
=> [STRMCMP-616] Improvements to integration test stability

deploy/crd.yaml, docs/crd.md, integ/test_app.yaml, pkg/controller/flink/config.go, pkg/controller/flink/config_test.go, pkg/controller/flink/flink_test.go, pkg/controller/flink/job_manager_controller_test.go, pkg/controller/flink/task_manager_controller_test.go
**Note that this is a breaking change, and will cause redeploy of all flink applications**
This PR fixes how we render Flink heap settings in the config based on the container memory requests and the configured `offHeapMemoryFraction`. This addresses #97, but also fixes a deeper issue where our memory settings were just being ignored.
This is a breaking change which is unfortunate, but also unavoidable in this case, as the current configuration is broken.
Currently we compute the Flink heap settings as `(1 - offHeapMemoryFraction) * requestedMemory`, convert it as a float to MB, then render it in the config like
```
jobmanager.heap.size: 1024
```
However this the wrong format and is ignored, at least by Flink 1.8; it should actually be 
```
jobmanager.heap.size: 1024m
````
In the case of …
=> [#97] [STRMCMP-648] [BREAKING] Fix rendering of flink memory configs

pkg/controller/flink/flink.go, pkg/controller/flink/flink_test.go, pkg/controller/flink/mock/mock_error_handler.go, pkg/controller/flink/mock/mock_flink.go, pkg/controller/flinkapplication/flink_state_machine.go, pkg/controller/flinkapplication/flink_state_machine_test.go
This PR fixes a bug that could lead to multiple jobs being submitted during the SubmittingJob phase. This would happen if a job was failing during the deploy process; because the activeJobs filter was excluding failing jobs, the operator would think that there was no job running and would resubmit another.
I've also taken this opportunity to make the operator more opinionated about _which_ job it's managing in the cluster. Whereas previously we would query for all jobs in the cluster and take the first "active" one, we now rely on the jobId we've stored in our state to determine which is our job. 
If this changes somehow from underneath us (like if the user cancels the job through the API and submits a new job) we should not continue on as if everything is well, as future operations are …
=> [STRMCMP-661] Fix bug that could lead to multiple job submission

pkg/controller/k8/cluster.go
Currently we have a single error metric for update failures. This PR adds a separate metric for conflicts, which are a client error and do not indicate anything is wrong with the api server.
=> Use a separate error metric for update conflicts

pkg/controller/flink/client/api.go, pkg/controller/flink/client/api_test.go
This PR adds another case to our immediate rollback (i.e., unretryable error) logic, that catches the case where the job submission fails. This typically happens due to an incompatible savepoint or an invalid jobgraph.
=> [STRMCMP-639] Trigger immediate rollback when job submission fails

README.md, deploy/crd.yaml, docs/crd.md, integ/simple_test.go, pkg/apis/app/v1beta1/types.go, pkg/controller/flink/flink.go, pkg/controller/flink/flink_test.go, pkg/controller/flink/mock/mock_flink.go, pkg/controller/flinkapplication/flink_state_machine.go, pkg/controller/flinkapplication/flink_state_machine_test.go, pkg/controller/k8/cluster.go, pkg/controller/k8/mock/mock_k8.go
This PR enables the [status subresource](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#status-subresource) for the FlinkApplication CRD. This makes it harder for users to accidentally overwrite status fields while trying to update their applications (an issue we've seen internally). For CRDs with the status subresource enabled, updates to the base resource will ignore changes to the status subrecord, and updates the status subresource will ignore changes to the spec and metadata.
The bulk of this PR is a set of changes that enables that one. Previously, the operator would modify the `SavepointInfo` field of the spec during updates. This goes against the general principle that the user should own the spec, and prevented a move to the …
=> [STRMCMP-675] Enable status subresource in CRD

examples/wordcount/flink-conf.yaml
If I get a +1, will create and push image to dockerhub, and update the custom resource
Tested locally:
```NAME                                           READY   STATUS    RESTARTS   AGE
kubecon-example-3d0dcfc7-jm-6b97cb766b-vmtwz   1/1     Running   0          2m20s
kubecon-example-3d0dcfc7-tm-dd9fd9c75-bzdmc    1/1     Running   0          2m20s
kubecon-example-3d0dcfc7-tm-dd9fd9c75-sf4hj    1/1     Running   0          2m20s
2019-11-21 19:44:33,630 INFO  org.apache.flink.runtime.taskexecutor.slot.TaskSlotTable      - Free slot TaskSlot(index:0, state:ACTIVE, resource profile: ResourceProfile{cpuCores=1.7976931348623157E308, heapMemoryInMB=2147483647, directMemoryInMB=2147483647, nativeMemoryInMB=2147483647, networkMemoryInMB=2147483647}, allocationId: 394c327efe5cb48ead40e564a327a26c, …
```
=> Fix the wordcount example Flink config

pkg/controller/flink/client/api.go, pkg/controller/flinkapplication/flink_state_machine.go, pkg/controller/flinkapplication/flink_state_machine_test.go
**Problem** 
- Deploy starts — Savepoint is triggered and triggerID registered
- `GetSavepointStatus` call keeps failing for whatever reason
-  Retries are exhausted for `GetSavepointStatus`, however we have[ no real way to progress ](https://github.com/lyft/flinkk8soperator/blob/master/pkg/controller/flinkapplication/flink_state_machine.go#L315)after this. The app gets stuck in a Savepointing Phase.
- User tries to force delete the application. However, with retry counts not being reset and a non-nil LastSeenError, the operator never handles the Deleting phase (i.e. [isTimeToHandlePhase](https://github.com/lyft/flinkk8soperator/blob/master/pkg/controller/flinkapplication/flink_state_machine.go#L196) always evaluates to false).
The PR fixes these problems in the following way:
- Reduces …
=> Fixes to ensure Delete phase is always handled and prevent deploys from being stuck in a Savepointing phase

integ/utils/utils.go, pkg/apis/app/v1beta1/types.go, pkg/controller/flink/client/api.go, pkg/controller/flink/client/entities.go, pkg/controller/flink/flink.go, pkg/controller/flink/flink_test.go, pkg/controller/flinkapplication/flink_state_machine.go, pkg/controller/flinkapplication/flink_state_machine_test.go
Currently, the only condition for moving from ClusterStarting to Savepointing (at which point the job goes down) is that all JM/TM pods are up according to the deployment. However, various issues with the TM process or configuration can prevent them from actually registering with the JobManager and becoming available to run tasks. This can lead to extended downtime and can require manual intervention to fix. I've also added a check from the SubmittingJob -> Running transition that the tasks are actually running, which gives us a chance to automatically roll back if the job never successfully starts.
This PR also adds some more visibility into task-level status, so that users can tell if the job is really running (in Flink, a job can be in the Running state even if none of its tasks are …
=> Gate statemachine progress on taskmanager availability

README.md
tiny fix -- looks like a dot's missing in the project status section: `... and stability. While in Beta, ...`
=> Add missing dot to readme

deploy/crd.yaml, docs/crd.md, pkg/apis/app/v1beta1/types.go, pkg/controller/flink/config.go, pkg/controller/flink/flink.go, pkg/controller/flink/flink_test.go
Adding a new option `maxCheckpointRestoreAgeSec` to configure checkpoint restoration age.
=> [STRMCMP-437] Making the checkpoint restoration age configurable

pkg/controller/flink/client/api.go, pkg/controller/flinkapplication/flink_state_machine.go
This fixes a bug that could lead to multiple job submissions in cases where there was an http-connection level error (e.g., a timeout).
Previously we were not calling `New()` on the resty package, which meant that we were using a single instance of the resty client across all calls. The meant that when we configured it for any call, the same configuration was used for subsequent calls. In particular, that meant that once we did a Get call, setting the number of retries to 3, that policy was applied to all subsequent calls, including POSTs, which should never be automatically retried. When a timeout occurred, this could then lead to multiple job submissions as the POST request was retried.
=> [STRMCMP-771] Properly initialize http client to fix multiple submission issue

deploy/crd.yaml, docs/crd.md, pkg/apis/app/v1beta1/types.go, pkg/controller/flink/flink_test.go, pkg/controller/flink/job_manager_controller.go, pkg/controller/flink/job_manager_controller_test.go, pkg/controller/flink/task_manager_controller.go, pkg/controller/flink/task_manager_controller_test.go
* Updating the CRD to enable pod security context to be specified and applied to JM and TM pods.
* Adding security context fields to crd validation.
* Changing security context injection to maintain hash-based backwards compatibility.
* Adding tests to ensure that security context is being injected properly.
=> Enabling PodSecurityContext to be configured for JM and TM pod templates

deploy/role.yaml
```
{"json":{"app_name":"wordcount-operator-example","ns":"team1","phase":""},"level":"error","msg":"K8s object update failed flinkapplications.flink.k8s.io \"wordcount-operator-example\" is forbidden: User \"system:serviceaccount:flink-operator:flinkoperator\" cannot update resource \"flinkapplications/status\" in API group \"flink.k8s.io\" in the namespace \"team1\"",
"ts":"2020-01-17T16:38:34Z"}
```
related to https://github.com/lyft/flinkk8soperator/issues/161
=> Add status subresource permission for Operator

pkg/controller/flinkapplication/flink_state_machine.go, pkg/controller/flinkapplication/flink_state_machine_test.go
If we time out after the new job has been submitted (generally because the tasks are never all running, possibly due to parallelism being misconfigured), we will enter the rollback phase. However, because the new job _was_ submitted, the jobID is set in our status, and so [this check|https://github.com/lyft/flinkk8soperator/blob/4142437353666b8692e62acf075a9b2c70514dd9/pkg/controller/flinkapplication/flink_state_machine.go#L396] prevents us from submitting the job to the old cluster.
This PR fixes that issue by clearing the jobId before moving to the RollingBack phase.
=> [STRMCMP-844] Fix rollback when SubmittingJob times out

pkg/controller/flinkapplication/flink_state_machine.go
Currently, all transitions to deployFailed production a `Successfully rolled back deploy` event (via the FlinkStateMachine.deployFailed method). However, there are some cases where the rollback in fact has failed; for example in the sequence where
1. cancelling the existing job succeeds, but we fail to find the savepoint path for some reason
2. there's never been a successful checkpoint taken for the job (or we fail to query it), so recovery fails
This change improves the error message in those cases to be clearer to the user that rollback has failed, and manual intervention is needed to recover.
Also includes a nil-pointer deference bug fix for the output of `GetJobForApplication`, which I encountered while reproducing this.
=> [STRMCMP-825] Improve error messaging when moving to DeployFailed in a non-recoverable state

pkg/apis/app/v1beta1/types.go, pkg/apis/app/v1beta1/zz_generated.deepcopy.go, pkg/controller/flink/job_manager_controller.go, pkg/controller/flink/job_manager_controller_test.go, pkg/controller/flink/task_manager_controller.go, pkg/controller/flink/task_manager_controller_test.go
Adds support for setting tolerations on taskmanager and jobmanager pods. This is implemented as a pass-through configuration to the underlying deployment.
=> Add support for setting pod tolerations

deploy/crd.yaml, docs/crd.md
Follow-on from #181, adding validation rules for toleration configurations to our crd and adding the new fields to our documentation.
=> Update documentation and crd validation for pod tolerations

deploy/crd.yaml
A user created a flink config that had a map where an array was expected in the sysctls field of securityContext:
i.e., they had:
```yaml
securityContext:
sysctls:
net.ipv4.tcp_keepalive_time: "900"
net.ipv4.tcp_retries2: "8"
```
when it should have been:
```yaml
securityContext:
sysctls:
- name: net.ipv4.tcp_keepalive_time
value: "900"
- name: net.ipv4.tcp_retries2
value: "8"
```
This managed to take down the operator, which was spending all of its time logging this error:
```
E0507 00:24:06.711346       1 reflector.go:126] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1beta1.FlinkApplication: v1beta1.FlinkApplicationList.Items: []v1beta1.FlinkApplication: v1beta1.FlinkApplication.Spec: v1beta1.FlinkApplicationSpec.SecurityContext: …
```
=> [STRMCMP-944] Add proper validation for the sysctls field in securityContext

pkg/controller/flinkapplication/flink_state_machine.go
#209 changed how we associate pods with services; previously we used the `flink-app-hash` label, but in order to decouple hashes from deployments this was changed to the random `pod-deployment-selector`.
For versioned services, this change did not cause any issues, as new versioned services are created for each deploy. The generic (non-versioned) service, however is kept for the lifetime of an application and so needs to be "upgraded" to the new way of selecting pods. #209 included support for upgrading existing services by adding the `pod-deployment-selector` label. However, it did not remove the existing `flink-app-hash` label. This broke generic services for applications that had been deployed on a previous version of the operator.
This PR fixes that, by removing the flink-app-hash …
=> Remove old flink-app-hash selector from generic service

Gopkg.lock, Gopkg.toml, deploy/crd.yaml, docs/crd.md, integ/test_app.yaml, pkg/apis/app/v1alpha1/types.go, pkg/apis/app/v1alpha1/zz_generated.deepcopy.go, pkg/apis/app/v1beta1/types.go, pkg/apis/app/v1beta1/zz_generated.deepcopy.go, pkg/controller/flink/config.go, pkg/controller/flink/config_test.go, pkg/controller/flink/flink_test.go, pkg/controller/flink/job_manager_controller_test.go, pkg/controller/flink/task_manager_controller_test.go, pkg/controller/flinkapplication/flink_state_machine_test.go
The memory setup has changed a lot with the 1.10 release for TaskManagers and with the 1.11 release for JobManagers.
The options set by the operator (`jobmanager.heap.size` and `taskmanager.heap.size`) are now deprecated. They can still be used in order to maintain backwards compatibility but they will be interpreted as a different option. Full migration guide can be found [here](https://ci.apache.org/projects/flink/flink-docs-master/ops/memory/mem_migration.html#migration-guide).
With this change, when the version of Flink that we are deploying is lower than 1.11 nothing will change: memory options will be computed as it was before.
When the Flink version is 1.11 or above, we will set `jobmanager.memory.process.size` and `taskmanager.memory.process.size` using the user defined requested …
=> Adapt to Flink v1.11 memory configuration

pkg/controller/flink/client/api.go
If the job submission POST request hits our 1 minute timeout (typically because the main method of the job, which needs to run to produce the job graph before job submission can complete) we can end up with two jobs submitted to the cluster.
The sequence of events looks like this:
1. We POST to /run
2. The POST times out
3. We retry the submission, POSTing to /run
4. The JobManager finishes job submission from the first request
5. The JobManager finishes job submission from the second request
Given that, after a timeout, we have no way to know if the job submission is still in progress on the JM, the only safe behavior in this case is to fail the deploy and rollback to the previous version.
This PR adopts that behavior, and also increases the timeout to 5 minutes which should hopefully …
=> Increase job submission timeout and fast fail when it occurs

pkg/controller/flinkapplication/flink_state_machine.go, pkg/controller/flinkapplication/flink_state_machine_test.go
**Issue**
There was a bug when the operator is trying to deploy an app when the previous deployment didn't work. The fetch for deployments resulted in `nil` with in-turn caused the operator to panic because the lack of handling of the `nil` case.
**Fix**
Added a check for `nil` deployments which now returns an error and fails the deployment.
=> [STRMCMP-1133] Fix for handling nil deployments

docs/crd.md, pkg/apis/app/v1beta1/types.go, pkg/controller/flink/config.go, pkg/controller/flink/config_test.go, pkg/controller/flink/flink_test.go, pkg/controller/flink/job_manager_controller_test.go, pkg/controller/flink/task_manager_controller_test.go, pkg/controller/flinkapplication/flink_state_machine_test.go
This fixes a regression introduced in #207 which caused us to use the wrong default for heap memory configs in Flink <1.11.
It also simplifies the memory configuration situation a bit. Now, for Flink <1.11 you may only configure memory with the existing `offHeapMemoryFraction` (which translates into `jobmanager.heap.size`/`taskmanager.heap.size`) and for version >= 1.11 you may only use the new `systemMemoryFraction` (which translates to `jobmanager.memory.process.size`/`taskmanager.memory.process.size`). Using an incompatible configuration for the specified `flinkVersion` will produce an error.
=> Fix regression in handling of default heap memory config

deploy/crd.yaml, docs/crd.md, pkg/apis/app/v1beta1/types.go, pkg/apis/app/v1beta1/zz_generated.deepcopy.go, pkg/controller/flink/job_manager_controller.go, pkg/controller/flink/task_manager_controller.go
Add affinity field to taskManagerConfig and jobManagerConfig to be able to set up affinity on pods.
Affinity fields are pass to the corresponding deployments.
openAPIV3Schema of affinity is built based on k8s open api.
=> Introduce affinity field

pkg/controller/flink/ingress.go, pkg/controller/flink/job_manager_controller_test.go
Instructions based on https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
=> Migrate to networking.k8s.io

deploy/crd.yaml, deploy/role-binding.yaml
This reverts commit 773b378f5f8cfa9758e3794b62c8e5fa00020606.
Removing this as v1 CRD's breaks integration tests which are using an old k8s client. Will save this for when we do the 1.22 upgrade in the near future
=> Revert "Support kubernetes 1.22 (#258)"

pkg/controller/flinkapplication/flink_state_machine.go
Fix a potential bug. If any vertex is failed, also need to set `allVerticesRunning` parameter to false explicitly. 
Currently this will not cause any issue because caller ignores `allVerticesRunning` if `hasFailure` is true. 
But future caller may make wrong assumption.
=> fix a potential bug

pkg/controller/flink/ingress.go, pkg/controller/flink/job_manager_controller_test.go
networking.k8s.io/v1beta1 API versions of Ingress is no longer served as of v1.22. upgrade to v1
Error: `Failed to create job managers for deploy 0cefa86b: no matches for kind "Ingress" in version "networking.k8s.io/v1beta1"`
=> [STRMCMP-1659] k8s 1.24 upgrade networking fix

pkg/controller/flinkapplication/flink_state_machine.go, pkg/controller/flinkapplication/flink_state_machine_test.go
Once a new Flink job is submitted, it’s possible that the job vertices are not in the running state by the configured timeout period of 3 minutes.
There exists a bug in the flinkk8scontroller where the app will get stuck in this phase, instead of being rolled back and marked as DeployFailed.
Slack [thread](https://lyft.slack.com/archives/CPN3NG47M/p1701461663432759?thread_ts=1701458116.814489&cid=CPN3NG47M)
=> Change app status to rollback on job start timeout

integ/test.sh, pkg/controller/flink/job_manager_controller.go
Change services to headless service as ClusterIP is not required. Apache OSS operator also uses headless services.
=> Headless Service

pkg/controller/flink/container_utils.go, pkg/controller/flink/job_manager_controller_test.go, pkg/controller/flink/task_manager_controller_test.go
The flink High availability should be using `kuberentes.cluster-id` instead of `high-availability.cluster-id` 
Here's the settings: 
https://nightlies.apache.org/flink/flink-docs-release-1.16/docs/deployment/ha/kubernetes_ha/
It seems like in 1.13 is already the same config:
https://nightlies.apache.org/flink/flink-docs-release-1.13/docs/deployment/ha/kubernetes_ha/
=> fix High availability config to be kubernetes.cluster-id
